//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.14 at 03:21:54 PM IDT 
//


package v8;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the v8 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InvoiceLines_QNAME = new QName("V8", "InvoiceLines");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: v8
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceLine }
     * 
     */
    public InvoiceLine createInvoiceLine() {
        return new InvoiceLine();
    }

    /**
     * Create an instance of {@link ArrayOfKeyValuePair }
     * 
     */
    public ArrayOfKeyValuePair createArrayOfKeyValuePair() {
        return new ArrayOfKeyValuePair();
    }

    /**
     * Create an instance of {@link KeyValuePair }
     * 
     */
    public KeyValuePair createKeyValuePair() {
        return new KeyValuePair();
    }

    /**
     * Create an instance of {@link TipaltiGLAccount }
     * 
     */
    public TipaltiGLAccount createTipaltiGLAccount() {
        return new TipaltiGLAccount();
    }

    /**
     * Create an instance of {@link ArrayOfTipaltiRelatedPurchaseOrder }
     * 
     */
    public ArrayOfTipaltiRelatedPurchaseOrder createArrayOfTipaltiRelatedPurchaseOrder() {
        return new ArrayOfTipaltiRelatedPurchaseOrder();
    }

    /**
     * Create an instance of {@link TipaltiRelatedPurchaseOrder }
     * 
     */
    public TipaltiRelatedPurchaseOrder createTipaltiRelatedPurchaseOrder() {
        return new TipaltiRelatedPurchaseOrder();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceLine }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InvoiceLine }{@code >}
     */
    @XmlElementDecl(namespace = "V8", name = "InvoiceLines")
    public JAXBElement<InvoiceLine> createInvoiceLines(InvoiceLine value) {
        return new JAXBElement<InvoiceLine>(_InvoiceLines_QNAME, InvoiceLine.class, null, value);
    }

}
