//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.14 at 03:21:54 PM IDT 
//


package org.tipalti;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfTipaltiGrnItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfTipaltiGrnItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TipaltiGrnItem" type="{http://Tipalti.org/}TipaltiGrnItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfTipaltiGrnItem", propOrder = {
    "tipaltiGrnItem"
})
public class ArrayOfTipaltiGrnItem {

    @XmlElement(name = "TipaltiGrnItem", nillable = true)
    protected List<TipaltiGrnItem> tipaltiGrnItem;

    /**
     * Gets the value of the tipaltiGrnItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tipaltiGrnItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTipaltiGrnItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipaltiGrnItem }
     * 
     * 
     */
    public List<TipaltiGrnItem> getTipaltiGrnItem() {
        if (tipaltiGrnItem == null) {
            tipaltiGrnItem = new ArrayList<TipaltiGrnItem>();
        }
        return this.tipaltiGrnItem;
    }

}
