//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.14 at 03:21:54 PM IDT 
//


package org.tipalti;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CreateOrUpdateGrnsResult" type="{http://Tipalti.org/}CreateOrUpdateGrnResult" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "createOrUpdateGrnsResult"
})
@XmlRootElement(name = "CreateOrUpdateGrnsResponse")
public class CreateOrUpdateGrnsResponse {

    @XmlElement(name = "CreateOrUpdateGrnsResult")
    protected CreateOrUpdateGrnResult createOrUpdateGrnsResult;

    /**
     * Gets the value of the createOrUpdateGrnsResult property.
     * 
     * @return
     *     possible object is
     *     {@link CreateOrUpdateGrnResult }
     *     
     */
    public CreateOrUpdateGrnResult getCreateOrUpdateGrnsResult() {
        return createOrUpdateGrnsResult;
    }

    /**
     * Sets the value of the createOrUpdateGrnsResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateOrUpdateGrnResult }
     *     
     */
    public void setCreateOrUpdateGrnsResult(CreateOrUpdateGrnResult value) {
        this.createOrUpdateGrnsResult = value;
    }

}
