//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.14 at 03:21:54 PM IDT 
//


package org.tipalti;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateOrUpdateTaxCodesResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateOrUpdateTaxCodesResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://Tipalti.org/}TipaltiResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TaxCodes" type="{http://Tipalti.org/}ArrayOfTipaltiTaxCode" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateOrUpdateTaxCodesResult", propOrder = {
    "taxCodes"
})
public class CreateOrUpdateTaxCodesResult
    extends TipaltiResponse
{

    @XmlElement(name = "TaxCodes")
    protected ArrayOfTipaltiTaxCode taxCodes;

    /**
     * Gets the value of the taxCodes property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTipaltiTaxCode }
     *     
     */
    public ArrayOfTipaltiTaxCode getTaxCodes() {
        return taxCodes;
    }

    /**
     * Sets the value of the taxCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTipaltiTaxCode }
     *     
     */
    public void setTaxCodes(ArrayOfTipaltiTaxCode value) {
        this.taxCodes = value;
    }

}
