//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.14 at 03:21:54 PM IDT 
//


package org.tipalti;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="payerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="paymentGroupTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tipaltiPaymentsOrders" type="{http://Tipalti.org/}ArrayOfTipaltiPaymentOrderItem" minOccurs="0"/&gt;
 *         &lt;element name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "payerName",
    "paymentGroupTitle",
    "tipaltiPaymentsOrders",
    "timeStamp",
    "key"
})
@XmlRootElement(name = "ProcessPaymentsAsync")
public class ProcessPaymentsAsync {

    protected String payerName;
    protected String paymentGroupTitle;
    protected ArrayOfTipaltiPaymentOrderItem tipaltiPaymentsOrders;
    protected double timeStamp;
    protected String key;

    /**
     * Gets the value of the payerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * Sets the value of the payerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerName(String value) {
        this.payerName = value;
    }

    /**
     * Gets the value of the paymentGroupTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentGroupTitle() {
        return paymentGroupTitle;
    }

    /**
     * Sets the value of the paymentGroupTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentGroupTitle(String value) {
        this.paymentGroupTitle = value;
    }

    /**
     * Gets the value of the tipaltiPaymentsOrders property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTipaltiPaymentOrderItem }
     *     
     */
    public ArrayOfTipaltiPaymentOrderItem getTipaltiPaymentsOrders() {
        return tipaltiPaymentsOrders;
    }

    /**
     * Sets the value of the tipaltiPaymentsOrders property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTipaltiPaymentOrderItem }
     *     
     */
    public void setTipaltiPaymentsOrders(ArrayOfTipaltiPaymentOrderItem value) {
        this.tipaltiPaymentsOrders = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     */
    public double getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     */
    public void setTimeStamp(double value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

}
