//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.14 at 03:21:54 PM IDT 
//


package org.tipalti;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipaltiGetPayeeInvoicesListDetailsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipaltiGetPayeeInvoicesListDetailsResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://Tipalti.org/}TipaltiResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InvoiceErrors" type="{http://Tipalti.org/}ArrayOfTipaltiInvoiceItemError" minOccurs="0"/&gt;
 *         &lt;element name="Invoices" type="{http://Tipalti.org/}ArrayOfTipaltiInvoiceItemResponse" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipaltiGetPayeeInvoicesListDetailsResponse", propOrder = {
    "invoiceErrors",
    "invoices"
})
public class TipaltiGetPayeeInvoicesListDetailsResponse
    extends TipaltiResponse
{

    @XmlElement(name = "InvoiceErrors")
    protected ArrayOfTipaltiInvoiceItemError invoiceErrors;
    @XmlElement(name = "Invoices")
    protected ArrayOfTipaltiInvoiceItemResponse invoices;

    /**
     * Gets the value of the invoiceErrors property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTipaltiInvoiceItemError }
     *     
     */
    public ArrayOfTipaltiInvoiceItemError getInvoiceErrors() {
        return invoiceErrors;
    }

    /**
     * Sets the value of the invoiceErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTipaltiInvoiceItemError }
     *     
     */
    public void setInvoiceErrors(ArrayOfTipaltiInvoiceItemError value) {
        this.invoiceErrors = value;
    }

    /**
     * Gets the value of the invoices property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTipaltiInvoiceItemResponse }
     *     
     */
    public ArrayOfTipaltiInvoiceItemResponse getInvoices() {
        return invoices;
    }

    /**
     * Sets the value of the invoices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTipaltiInvoiceItemResponse }
     *     
     */
    public void setInvoices(ArrayOfTipaltiInvoiceItemResponse value) {
        this.invoices = value;
    }

}
