//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.14 at 03:21:54 PM IDT 
//


package org.tipalti;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipaltiGlAccountAction.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipaltiGlAccountAction"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Update"/&gt;
 *     &lt;enumeration value="Close"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TipaltiGlAccountAction")
@XmlEnum
public enum TipaltiGlAccountAction {

    @XmlEnumValue("Update")
    UPDATE("Update"),
    @XmlEnumValue("Close")
    CLOSE("Close");
    private final String value;

    TipaltiGlAccountAction(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipaltiGlAccountAction fromValue(String v) {
        for (TipaltiGlAccountAction c: TipaltiGlAccountAction.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
