//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.14 at 03:21:54 PM IDT 
//


package org.tipalti;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipaltiCustomField complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipaltiCustomField"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Action" type="{http://Tipalti.org/}CustomFieldAction"/&gt;
 *         &lt;element name="Entity" type="{http://Tipalti.org/}CustomFieldEntity"/&gt;
 *         &lt;element name="SubEntity" type="{http://Tipalti.org/}CustomFieldSubEntity"/&gt;
 *         &lt;element name="Type" type="{http://Tipalti.org/}CustomFieldType"/&gt;
 *         &lt;element name="IframeDisplay" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Values" type="{http://Tipalti.org/}ArrayOfCustomFieldValue" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipaltiCustomField", propOrder = {
    "title",
    "description",
    "action",
    "entity",
    "subEntity",
    "type",
    "iframeDisplay",
    "values"
})
public class TipaltiCustomField {

    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Action", required = true)
    @XmlSchemaType(name = "string")
    protected CustomFieldAction action;
    @XmlElement(name = "Entity", required = true)
    @XmlSchemaType(name = "string")
    protected CustomFieldEntity entity;
    @XmlElement(name = "SubEntity", required = true, nillable = true)
    @XmlSchemaType(name = "string")
    protected CustomFieldSubEntity subEntity;
    @XmlElement(name = "Type", required = true)
    @XmlSchemaType(name = "string")
    protected CustomFieldType type;
    @XmlElement(name = "IframeDisplay", required = true, type = Boolean.class, nillable = true)
    protected Boolean iframeDisplay;
    @XmlElement(name = "Values")
    protected ArrayOfCustomFieldValue values;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link CustomFieldAction }
     *     
     */
    public CustomFieldAction getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomFieldAction }
     *     
     */
    public void setAction(CustomFieldAction value) {
        this.action = value;
    }

    /**
     * Gets the value of the entity property.
     * 
     * @return
     *     possible object is
     *     {@link CustomFieldEntity }
     *     
     */
    public CustomFieldEntity getEntity() {
        return entity;
    }

    /**
     * Sets the value of the entity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomFieldEntity }
     *     
     */
    public void setEntity(CustomFieldEntity value) {
        this.entity = value;
    }

    /**
     * Gets the value of the subEntity property.
     * 
     * @return
     *     possible object is
     *     {@link CustomFieldSubEntity }
     *     
     */
    public CustomFieldSubEntity getSubEntity() {
        return subEntity;
    }

    /**
     * Sets the value of the subEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomFieldSubEntity }
     *     
     */
    public void setSubEntity(CustomFieldSubEntity value) {
        this.subEntity = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CustomFieldType }
     *     
     */
    public CustomFieldType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomFieldType }
     *     
     */
    public void setType(CustomFieldType value) {
        this.type = value;
    }

    /**
     * Gets the value of the iframeDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIframeDisplay() {
        return iframeDisplay;
    }

    /**
     * Sets the value of the iframeDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIframeDisplay(Boolean value) {
        this.iframeDisplay = value;
    }

    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCustomFieldValue }
     *     
     */
    public ArrayOfCustomFieldValue getValues() {
        return values;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCustomFieldValue }
     *     
     */
    public void setValues(ArrayOfCustomFieldValue value) {
        this.values = value;
    }

}
