//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.14 at 03:21:54 PM IDT 
//


package org.tipalti;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TipaltiPurchaseOrderItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipaltiPurchaseOrderItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Idap" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PurchaseOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://Tipalti.org/}eUploadCenterRecordStatus"/&gt;
 *         &lt;element name="Memo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PurchaseOrderDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="PayerEntity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Approvers" type="{http://Tipalti.org/}ArrayOfTipaltiInvoiceApprover" minOccurs="0"/&gt;
 *         &lt;element name="CustomFields" type="{http://Tipalti.org/}ArrayOfKeyValuePair" minOccurs="0"/&gt;
 *         &lt;element name="PurchaseOrderLines" type="{http://Tipalti.org/}ArrayOfPurchaseOrderLine" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipaltiPurchaseOrderItem", propOrder = {
    "idap",
    "purchaseOrderNumber",
    "status",
    "memo",
    "purchaseOrderDate",
    "payerEntity",
    "currency",
    "approvers",
    "customFields",
    "purchaseOrderLines"
})
public class TipaltiPurchaseOrderItem {

    @XmlElement(name = "Idap")
    protected String idap;
    @XmlElement(name = "PurchaseOrderNumber")
    protected String purchaseOrderNumber;
    @XmlElement(name = "Status", required = true)
    @XmlSchemaType(name = "string")
    protected EUploadCenterRecordStatus status;
    @XmlElement(name = "Memo")
    protected String memo;
    @XmlElement(name = "PurchaseOrderDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar purchaseOrderDate;
    @XmlElement(name = "PayerEntity")
    protected String payerEntity;
    @XmlElement(name = "Currency")
    protected String currency;
    @XmlElement(name = "Approvers")
    protected ArrayOfTipaltiInvoiceApprover approvers;
    @XmlElement(name = "CustomFields")
    protected ArrayOfKeyValuePair customFields;
    @XmlElement(name = "PurchaseOrderLines")
    protected ArrayOfPurchaseOrderLine purchaseOrderLines;

    /**
     * Gets the value of the idap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdap() {
        return idap;
    }

    /**
     * Sets the value of the idap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdap(String value) {
        this.idap = value;
    }

    /**
     * Gets the value of the purchaseOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseOrderNumber() {
        return purchaseOrderNumber;
    }

    /**
     * Sets the value of the purchaseOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseOrderNumber(String value) {
        this.purchaseOrderNumber = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link EUploadCenterRecordStatus }
     *     
     */
    public EUploadCenterRecordStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link EUploadCenterRecordStatus }
     *     
     */
    public void setStatus(EUploadCenterRecordStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the memo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemo() {
        return memo;
    }

    /**
     * Sets the value of the memo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemo(String value) {
        this.memo = value;
    }

    /**
     * Gets the value of the purchaseOrderDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPurchaseOrderDate() {
        return purchaseOrderDate;
    }

    /**
     * Sets the value of the purchaseOrderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPurchaseOrderDate(XMLGregorianCalendar value) {
        this.purchaseOrderDate = value;
    }

    /**
     * Gets the value of the payerEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerEntity() {
        return payerEntity;
    }

    /**
     * Sets the value of the payerEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerEntity(String value) {
        this.payerEntity = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the approvers property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTipaltiInvoiceApprover }
     *     
     */
    public ArrayOfTipaltiInvoiceApprover getApprovers() {
        return approvers;
    }

    /**
     * Sets the value of the approvers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTipaltiInvoiceApprover }
     *     
     */
    public void setApprovers(ArrayOfTipaltiInvoiceApprover value) {
        this.approvers = value;
    }

    /**
     * Gets the value of the customFields property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfKeyValuePair }
     *     
     */
    public ArrayOfKeyValuePair getCustomFields() {
        return customFields;
    }

    /**
     * Sets the value of the customFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfKeyValuePair }
     *     
     */
    public void setCustomFields(ArrayOfKeyValuePair value) {
        this.customFields = value;
    }

    /**
     * Gets the value of the purchaseOrderLines property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfPurchaseOrderLine }
     *     
     */
    public ArrayOfPurchaseOrderLine getPurchaseOrderLines() {
        return purchaseOrderLines;
    }

    /**
     * Sets the value of the purchaseOrderLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfPurchaseOrderLine }
     *     
     */
    public void setPurchaseOrderLines(ArrayOfPurchaseOrderLine value) {
        this.purchaseOrderLines = value;
    }

}
