//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.14 at 03:21:54 PM IDT 
//


package org.tipalti;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TipaltiInvoiceItemRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipaltiInvoiceItemRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Idap" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InvoiceRefCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InvoiceDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="InvoiceDueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="InvoiceLines" type="{http://Tipalti.org/}ArrayOfInvoiceLine" minOccurs="0"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CanApprove" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="InvoiceInternalNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomFields" type="{http://Tipalti.org/}ArrayOfKeyValuePair" minOccurs="0"/&gt;
 *         &lt;element name="IsPaidManually" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IncomeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InvoiceStatus" type="{http://Tipalti.org/}TipaltiInvoiceStatus"/&gt;
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Approvers" type="{http://Tipalti.org/}ArrayOfTipaltiInvoiceApprover" minOccurs="0"/&gt;
 *         &lt;element name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PayerEntityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InvoiceSubject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ApAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ApAccountExternalId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipaltiInvoiceItemRequest", propOrder = {
    "idap",
    "invoiceRefCode",
    "invoiceDate",
    "invoiceDueDate",
    "invoiceLines",
    "description",
    "canApprove",
    "invoiceInternalNotes",
    "customFields",
    "isPaidManually",
    "incomeType",
    "invoiceStatus",
    "currency",
    "approvers",
    "invoiceNumber",
    "payerEntityName",
    "invoiceSubject",
    "apAccountNumber",
    "apAccountExternalId"
})
public class TipaltiInvoiceItemRequest {

    @XmlElement(name = "Idap")
    protected String idap;
    @XmlElement(name = "InvoiceRefCode")
    protected String invoiceRefCode;
    @XmlElement(name = "InvoiceDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar invoiceDate;
    @XmlElement(name = "InvoiceDueDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar invoiceDueDate;
    @XmlElement(name = "InvoiceLines")
    protected ArrayOfInvoiceLine invoiceLines;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "CanApprove")
    protected boolean canApprove;
    @XmlElement(name = "InvoiceInternalNotes")
    protected String invoiceInternalNotes;
    @XmlElement(name = "CustomFields")
    protected ArrayOfKeyValuePair customFields;
    @XmlElement(name = "IsPaidManually")
    protected boolean isPaidManually;
    @XmlElement(name = "IncomeType")
    protected String incomeType;
    @XmlElement(name = "InvoiceStatus", required = true, nillable = true)
    @XmlSchemaType(name = "string")
    protected TipaltiInvoiceStatus invoiceStatus;
    @XmlElement(name = "Currency")
    protected String currency;
    @XmlElement(name = "Approvers")
    protected ArrayOfTipaltiInvoiceApprover approvers;
    @XmlElement(name = "InvoiceNumber")
    protected String invoiceNumber;
    @XmlElement(name = "PayerEntityName")
    protected String payerEntityName;
    @XmlElement(name = "InvoiceSubject")
    protected String invoiceSubject;
    @XmlElement(name = "ApAccountNumber")
    protected String apAccountNumber;
    @XmlElement(name = "ApAccountExternalId")
    protected String apAccountExternalId;

    /**
     * Gets the value of the idap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdap() {
        return idap;
    }

    /**
     * Sets the value of the idap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdap(String value) {
        this.idap = value;
    }

    /**
     * Gets the value of the invoiceRefCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceRefCode() {
        return invoiceRefCode;
    }

    /**
     * Sets the value of the invoiceRefCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceRefCode(String value) {
        this.invoiceRefCode = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceDate(XMLGregorianCalendar value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the invoiceDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceDueDate() {
        return invoiceDueDate;
    }

    /**
     * Sets the value of the invoiceDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceDueDate(XMLGregorianCalendar value) {
        this.invoiceDueDate = value;
    }

    /**
     * Gets the value of the invoiceLines property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfInvoiceLine }
     *     
     */
    public ArrayOfInvoiceLine getInvoiceLines() {
        return invoiceLines;
    }

    /**
     * Sets the value of the invoiceLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfInvoiceLine }
     *     
     */
    public void setInvoiceLines(ArrayOfInvoiceLine value) {
        this.invoiceLines = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the canApprove property.
     * 
     */
    public boolean isCanApprove() {
        return canApprove;
    }

    /**
     * Sets the value of the canApprove property.
     * 
     */
    public void setCanApprove(boolean value) {
        this.canApprove = value;
    }

    /**
     * Gets the value of the invoiceInternalNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceInternalNotes() {
        return invoiceInternalNotes;
    }

    /**
     * Sets the value of the invoiceInternalNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceInternalNotes(String value) {
        this.invoiceInternalNotes = value;
    }

    /**
     * Gets the value of the customFields property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfKeyValuePair }
     *     
     */
    public ArrayOfKeyValuePair getCustomFields() {
        return customFields;
    }

    /**
     * Sets the value of the customFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfKeyValuePair }
     *     
     */
    public void setCustomFields(ArrayOfKeyValuePair value) {
        this.customFields = value;
    }

    /**
     * Gets the value of the isPaidManually property.
     * 
     */
    public boolean isIsPaidManually() {
        return isPaidManually;
    }

    /**
     * Sets the value of the isPaidManually property.
     * 
     */
    public void setIsPaidManually(boolean value) {
        this.isPaidManually = value;
    }

    /**
     * Gets the value of the incomeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomeType() {
        return incomeType;
    }

    /**
     * Sets the value of the incomeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomeType(String value) {
        this.incomeType = value;
    }

    /**
     * Gets the value of the invoiceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TipaltiInvoiceStatus }
     *     
     */
    public TipaltiInvoiceStatus getInvoiceStatus() {
        return invoiceStatus;
    }

    /**
     * Sets the value of the invoiceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipaltiInvoiceStatus }
     *     
     */
    public void setInvoiceStatus(TipaltiInvoiceStatus value) {
        this.invoiceStatus = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the approvers property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTipaltiInvoiceApprover }
     *     
     */
    public ArrayOfTipaltiInvoiceApprover getApprovers() {
        return approvers;
    }

    /**
     * Sets the value of the approvers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTipaltiInvoiceApprover }
     *     
     */
    public void setApprovers(ArrayOfTipaltiInvoiceApprover value) {
        this.approvers = value;
    }

    /**
     * Gets the value of the invoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the payerEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerEntityName() {
        return payerEntityName;
    }

    /**
     * Sets the value of the payerEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerEntityName(String value) {
        this.payerEntityName = value;
    }

    /**
     * Gets the value of the invoiceSubject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceSubject() {
        return invoiceSubject;
    }

    /**
     * Sets the value of the invoiceSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceSubject(String value) {
        this.invoiceSubject = value;
    }

    /**
     * Gets the value of the apAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApAccountNumber() {
        return apAccountNumber;
    }

    /**
     * Sets the value of the apAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApAccountNumber(String value) {
        this.apAccountNumber = value;
    }

    /**
     * Gets the value of the apAccountExternalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApAccountExternalId() {
        return apAccountExternalId;
    }

    /**
     * Sets the value of the apAccountExternalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApAccountExternalId(String value) {
        this.apAccountExternalId = value;
    }

}
